# Publish this application to Bluemix using Ansible
---
- name: Publish the app to Bluemix
  hosts: localhost
  connection: local
  vars:
    pipeline_id: "{{ lookup('env','PIPELINE_ID') | default('test-php-sample-1',true) }}"
    app_hostname: "{{ lookup('env','APP_HOSTNAME') | default(pipeline_id,true) }}"
  tasks:
    - debug:
        var: app_hostname
    - name: CF Push Application
      shell: "cf push app_hostname }}"