---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: master
    service: ${SAMPLE_REPO}
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
- name: DEPLOY
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: APP_HOSTNAME
    value: undefined
    type: text
  jobs:
  - name: Ansible Deploy
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |
      #!/bin/bash
      # Install Ansible
      echo "Install Ansible"
      python --version
      echo "apt-get -qq update"
      sudo apt-get -qq update
      echo "apt-get -qq -y install python-dev libssl-dev libffi-dev"
      sudo apt-get -qq -y install python-dev libssl-dev libffi-dev
      echo "pip install pycrypto pyyaml ansible --quiet"
      sudo pip install pycrypto pyyaml ansible --quiet
      echo "apt-get -qq clean"
      sudo apt-get -qq clean

      export APP_HOSTNAME="$CF_APP"

      # Run Ansible playbook
      echo "Run Ansible playbook"
      ansible-playbook .playbook.yml
      echo "Ansible playbook complete"
#hooks:
#- enabled: true
#  label: null
#  ssl_enabled: false
#  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish      
      
